### ISSUE TITLE
merge to main after pushing to feedback?

### ISSUE THREAD

**Issue by sohamdata** [HousewareHQ/frontend-engineering-octernship#20]
I've made two commits and pushed to the feedback branch and made a PR. Should I merge with the main branch?
The task description: `Making changes on the auto generated feedback branch to complete the task`
pr: https://github.com/HousewareHQ/houseware---frontend-engineering-octernship-sohamdata/pull/2

**Comment by babboe1** [comment]
I think the instructions have been updated, we are asked to add our final changes to the main branch of our private repo, 
what I think is that after pushing to the feedback branch a PR should be made to the main branch,
since we were asked to add it to the main branch then i guess it ough't to be merged
